# ArgoCD Blue/Green 배포 예제

apiVersion: argoproj.io/v1alpha1     # apps/v1 대신 argoproj.io/v1alpha1을 사용한다
kind: Rollout  # Deplyment 대신 Rollout을 사용한다
metadata:
  name: marvelworld-bluegreen
  namespace: rollout
spec:
  replicas: 4
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: marvelworld-bluegreen
  template:
    metadata:
      labels:
        app: marvelworld-bluegreen
    spec:
      containers:
      - name: marvelworld-container
        image: hkh8308/marvelworld:1.0
      # image: hkh8308/marvelworld:2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
  strategy:
    blueGreen: 
      #activeService는 이전의 배포된 Blue 서비스
      activeService: marvelworld-bluegreen-active
      
      #previewService는 새롭게 배포될 Green 서비스
      previewService: marvelworld-bluegreen-preview
      
      #autoPromotioEnabled 옵션은 Blue/Green 배포를 자동으로 진행할 것인지 여부. false 옵션을 사용해 수동으로 지정
      autoPromotionEnabled: ture

---
kind: Service
apiVersion: v1
metadata:
  name: marvelworld-bluegreen-active
spec:
  selector:
    app: marvelworld-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---
kind: Service
apiVersion: v1
metadata:
  name: marvelworld-bluegreen-preview
spec:
  selector:
    app: marvelworld-bluegreen
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type : LoadBalancer
