apiVersion: apps/v1
kind: Deployment
metadata:
  name: marvelworld
  labels:
    app: marvelworld
spec:
  replicas: 0
  selector:
    matchLabels:
      app: marvelworld
  template:
    metadata:
      labels:
        app: marvelworld
    spec:
      containers:
      - name: marvelworld-container
        image: hkh8308/marvelworld:2.0
        ports:
        - containerPort: 8080
